language: ruby
rvm:
  - 2.5.1
bundler_args: --jobs=2
script:
script:
  - gem install bundler
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
  chrome: stable
